const queryKeys = {
  /** 유저 */
  USER_LIST: "USER_LIST",
  USER_DETAIL: "USER_DETAIL",
  USER_DISPATCHED: "USER_DISPATCHED",
  USER_GRADUATE: "USER_GRADUATE",
  USER_LINE_OUT: "USER_LINE_OUT",
  /** 텀 */
  TERM_CURRENT_DATA: "TERM_CURRENT_DATA",
  // TERM_CURRENT_ID: "TERM_CURRENT_ID",
  TERM_LIST: "TERM_LIST",
  TERM_DUTY_COUNT: "TERM_DUTY_COUNT",
  TERM_ALL_LEADERS: "TERM_ALL_LEADERS",
  TERM_PASTOR: "TERM_PASTOR",
  TERM_CODY: "TERM_CODY",
  TERM_CODY_AND_SMALL_GROUPS: "TERM_CODY_AND_SMALL_GROUPS",
  TERM_SMALL_GROUP_LEADER: "TERM_SMALL_GROUP_LEADER",
  TERM_NEW_FAMILY_LEADER: "TERM_NEW_FAMILY_LEADER",
  SMALL_GROUP_LEADER_BY_CODY: "SMALL_GROUP_LEADER_BY_CODY",
  NEW_FAMILY_GROUP_LEADER_BY_CODY: "NEW_FAMILY_GROUP_LEADER_BY_CODY",
  MEMBERS_BY_CODY: "MEMBERS_BY_CODY",
  /** 새가족 */
  NEW_FAMILY: "NEW_FAMILY",
  NEW_FAMILY_DETAIL: "NEW_FAMILY_DETAIL",
  NEW_FAMILY_LINE_UP_REQUEST: "NEW_FAMILY_LINE_UP_REQUEST",
  NEW_FAMILY_PROMOTED: "NEW_FAMILY_PROMOTED",
  NEW_FAMILY_LINE_OUT: "NEW_FAMILY_LINE_OUT",
  /** 새가족 출석 관련 */
  NEW_FAMILY_ATTENDANCE: "NEW_FAMILY_ATTENDANCE",
  // NEW_FAMILY_ATTENDANCE_CHECK: "NEW_FAMILY_ATTENDANCE_CHECK",

  /** 라인업 수정 관련 */
  LINE_UP_UPDATE: {
    SMALL_GROUP_MEMBERS: "SMALL_GROUP_MEMBERS",
    NEW_FAMILY_GROUP_MEMBERS: "NEW_FAMILY_GROUP_MEMBERS"
  },

  //   /** 출석 관련 */
  //   ATTENDANCE: "ATTENDANCE",
  //   ATTENDANCE_CHECK: "ATTENDANCE_CHECK",

  //   /** 계정 관련 */
  //   ACCOUNT: "ACCOUNT",
  //   ACCOUNT_DETAIL: "ACCOUNT_DETAIL",
  //   ACCOUNT_LEADERS: "ACCOUNT_LEADERS",
  //   ACCOUNT_ROLES: "ACCOUNT_ROLES",
  //   ACCOUNT_LOGIN: "ACCOUNT_LOGIN",
  ACCOUNT_INFO: "ACCOUNT_INFO"

  //   /** 텀 주차 통계 */
  //   TERM_STATISTICS: "TERM_STATISTICS",
  //   /** 텀 유저 통계 정보 */
  //   TERM_USER_STATISTICS: "TERM_USER_STATISTICS",

  //   /** 통계 관련 */
  //   STATISTICS_BASE: "STATISTICS_BASE",
  //   STATISTICS_ATTENDANCE: "STATISTICS_ATTENDANCE",
  //   STATISTICS_ATTENDANCE_BENCH: "STATISTICS_ATTENDANCE_BENCH",
  //   STATISTICS_ATTENDANCE_EXCEL: "STATISTICS_ATTENDANCE_EXCEL",
  //   STATISTICS_ATTENDANCE_PROGRESS: "STATISTICS_ATTENDANCE_PROGRESS",

  //   /** 명부 관련 */
  //   TRAINING_DETAIL: "TRAINING_DETAIL",
  //   TRAINING_MEMBERS: "TRAINING_MEMBERS",

  //   /***********************************************/
};

export default queryKeys;
