const queryKeys = {
//   TERM: "TERM",
//   /** 텀 코디 */
//   TERM_CORDI: "TERM_CORDI",
//   /** 텀 코디의 리더들 */
//   MEMBERS_BY_CODY: "MEMBERS_BY_CODY",
  /** 텀 새가족 */
  NEW_FAMILY: "NEW_FAMILY",
  NEW_FAMILY_DETAIL: "NEW_FAMILY_DETAIL",
  NEW_FAMILY_LINE_UP_REQUEST: "NEW_FAMILY_LINE_UP_REQUEST",
  NEW_FAMILY_PROMOTED: "NEW_FAMILY_PROMOTED",
  NEW_FAMILY_LINE_OUT: "NEW_FAMILY_LINE_OUT",
  /** 새가족 출석 관련 */
  NEW_FAMILY_ATTENDANCE: "NEW_FAMILY_ATTENDANCE",
  // NEW_FAMILY_ATTENDANCE_CHECK: "NEW_FAMILY_ATTENDANCE_CHECK",

//   /** 출석 관련 */
//   ATTENDANCE: "ATTENDANCE",
//   ATTENDANCE_CHECK: "ATTENDANCE_CHECK",

//   /** 계정 관련 */
//   ACCOUNT: "ACCOUNT",
//   ACCOUNT_DETAIL: "ACCOUNT_DETAIL",
//   ACCOUNT_LEADERS: "ACCOUNT_LEADERS",
//   ACCOUNT_ROLES: "ACCOUNT_ROLES",
//   ACCOUNT_LOGIN: "ACCOUNT_LOGIN",
  ACCOUNT_INFO: "ACCOUNT_INFO",

//   /** 텀 주차 통계 */
//   TERM_STATISTICS: "TERM_STATISTICS",
//   /** 텀 유저 통계 정보 */
//   TERM_USER_STATISTICS: "TERM_USER_STATISTICS",

//   /** 통계 관련 */
//   STATISTICS_BASE: "STATISTICS_BASE",
//   STATISTICS_ATTENDANCE: "STATISTICS_ATTENDANCE",
//   STATISTICS_ATTENDANCE_BENCH: "STATISTICS_ATTENDANCE_BENCH",
//   STATISTICS_ATTENDANCE_EXCEL: "STATISTICS_ATTENDANCE_EXCEL",
//   STATISTICS_ATTENDANCE_PROGRESS: "STATISTICS_ATTENDANCE_PROGRESS",

//   /** 명부 관련 */
//   TRAINING_DETAIL: "TRAINING_DETAIL",
//   TRAINING_MEMBERS: "TRAINING_MEMBERS",

//   /***********************************************/

//   /** V2 API */
//   NEW_FAMILY_V2: "NEW_FAMILY_V2",
//   NEW_FAMILY_LINE_OUT_V2: "NEW_FAMILY_LINE_OUT_V2",
//   NEW_FAMILY_DETAIL_V2: "NEW_FAMILY_DETAIL_V2",

  TERM_SMALL_GROUP_LEADER: "TERM_SMALL_GROUP_LEADER",
  TERM_NEW_FAMILY_LEADER: "TERM_NEW_FAMILY_LEADER"
};

export default queryKeys;
